### PR TITLE
Added detailed error messages for validateCovidPass function

### LINKED ISSUE #6: Return a set of well defined errors from `validateCovidPassport`
Currently Will is just returning false if a check fails.

For example in the spec it says

`Check if the payload received from the QR Code begins with the prefix NZCP:/, if it does not then fail.`

We should do something like

`return { success: false, code: 100, message: "Payload must begin with \"NZCP:/\""}`

### PR DESCRIPTION
**Pull request by J-eld**
Fixes #6 

Please review to check if error messages are valid and correct

- [x] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by wseagar** [comment]
Hey J-eld thank you so much for contributing - We're just working on the the API for this and I think we've settled with a different data structure to return for errors. @noway is working on it now but when were settled we'll be happy to keep working on this.

**Comment by J-eld** [comment]
No worries, thanks for letting me know. I'm new to open source but keen to contribute where I can. I'll keep an eye on the issues tab for anything I feel like I can contribute to.

**Comment by wseagar** [comment]
Decided to go for a different structure than referenced in the issue, it should be in now. I've got another task you can work on @J-eld I'll tag you in the issue

**Comment by wseagar** [comment]
#19 @J-eld do you want to take this ticket?

**Pull request closed without merging**
